// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awhhmtfzwzgjqgyqocgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aGhtdGZ6d3pnanFneXFvY2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjU4NjAsImV4cCI6MjA2OTgwMTg2MH0.ZVAHLatUz3DyFeOS_KVi_CrG19EfId69CW0bBbP_FPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});